functionsDirectory = "D:\\Projects\\ShiftTime_CRM_TEST__65-0001\\frontend\\netlify\\functions"
functionsDirectoryOrigin = "config-v1"
headersOrigin = "config"
redirectsOrigin = "config"
plugins = []

[build]
publish = "D:\\Projects\\ShiftTime_CRM_TEST__65-0001\\frontend"
publishOrigin = "config"
functions = "D:\\Projects\\ShiftTime_CRM_TEST__65-0001\\frontend\\netlify\\functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]

[[headers]]
for = "/*"

[headers.values]
Cache-Control = "no-store"

[[headers]]
for = "/*"

[headers.values]
Access-Control-Allow-Origin = "*"

[[redirects]]
from = "/api/config/kv"
to = "/.netlify/functions/config-links"
status = 200.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/api/config/links"
to = "/.netlify/functions/config-links"
status = 200.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/api/telegram/send"
to = "/.netlify/functions/send-telegram"
status = 200.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/api/telegram/edit"
to = "/.netlify/functions/edit-telegram"
status = 200.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/api/orders/set-status"
to = "/.netlify/functions/set-status"
status = 200.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/api/orders/set-ttn"
to = "/.netlify/functions/set-ttn"
status = 200.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/api/:name"
to = "/.netlify/functions/:name"
status = 200.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/api/auth"
to = "https://script.google.com/macros/s/AKfycbyfGKwSIEhASTWJaayjslWD6wOWDFYyznlmUFih9iofphjPBM4KZwaDdNluxeopkVtrfA/exec"
status = 200.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]
Access-Control-Allow-Origin = "*"