// /frontend/widgets/admin/theme.js
// Темізатор адмін-сторінки: працює ТІЛЬКИ з CSS-змінними в #admin-root через <style id="admin-theme-vars">

// ───────────────────────────────────────────────────────────────────────────────
// LocalStorage ключі
const LS_ACTIVE   = 'st_admin_theme_active';
const LS_PROFILES = 'st_admin_theme_profiles';

// ───────────────────────────────────────────────────────────────────────────────
// Найпростіші утиліти
const $  = (sel, root = document) => root.querySelector(sel);
const $$ = (sel, root = document) => Array.from(root.querySelectorAll(sel));

function safeGet(id) { return document.getElementById(id) || null; }
function val(id, fallback = '') {
  const el = safeGet(id);
  if (!el) return String(fallback);
  return String(el.value ?? fallback);
}
function toPx(n, fallback = '') {
  if (n === '' || n == null) return String(fallback);
  const v = Number(n);
  return Number.isFinite(v) ? `${v}px` : String(n);
}
function toPct(n, fallback = '') {
  if (n === '' || n == null) return String(fallback);
  const v = Number(n);
  return Number.isFinite(v) ? `${v}%` : String(n);
}
function toNum(n, fallback = 0) {
  const v = Number(n);
  return Number.isFinite(v) ? v : fallback;
}

function readJSON(key, fallback) {
  try { return JSON.parse(localStorage.getItem(key) || 'null') ?? fallback; }
  catch { return fallback; }
}
function writeJSON(key, data) {
  localStorage.setItem(key, JSON.stringify(data ?? {}));
}

// Стиль, куди кладемо CSS-змінні
const styleTag = (() => {
  let el = $('#admin-theme-vars');
  if (!el) {
    el = document.createElement('style');
    el.id = 'admin-theme-vars';
    document.head.appendChild(el);
  }
  return el;
})();

// ───────────────────────────────────────────────────────────────────────────────
// Збір значень з форми → CSS Variables Map
function collectVars() {
  return {
    /* Layout / сторінка */
    '--content-x'       : toPx(val('th-content-x', '24')),
    '--admin-gap'       : toPx(val('th-gap', '28')),
    '--sidebar-w'       : toPx(val('th-sidebar', '260')),
    '--offset-left'     : toPx(val('th-offset-left', '12')),
    '--panel-max-w'     : toPx(val('th-maxw', '1200')),
    '--table-w'         : toPct(val('th-tablew', '100')),



    /* Панель “Налаштування” (всередині картки) */
    '--settings-mt'     : toPx(val('th-panel-mt', '24')),
    '--settings-mb'     : toPx(val('th-panel-mb', '24')),
    '--footer-h'        : toPx(val('th-footer-h', '52')),

    // Розміри та масштаб спеціальної внутрішньої області (щоб не їхали контролі)
    '--settings-maxw'   : toPx(val('th-settings-maxw', '1600')),
    '--settings-width'  : toPx(val('th-settings-w', '1100')),
    '--settings-minw'   : toPx(val('th-settings-minw', '720')),
    '--settings-zoom'   : toNum(val('th-settings-zoom', '1')),
    '--settings-gap'    : toPx(val('th-settings-gap', '32')),
    '--settings-pad-x'  : toPx(val('th-settings-pad-x', '16')),

    /* Кольори */
    '--page-bg'         : val('th-c-page', '#0b0b0f'),
    '--text'            : val('th-c-text', '#ffffff'),
    '--muted'           : val('th-c-dim', '#a0a0a0'),
    '--accent'          : val('th-accent', '#ffffff'),

    /* Картки */
    '--card-bg'         : val('th-card-bg', '#111318'),
    '--card-br'         : val('th-card-br', '#2a2f3a'),
    '--card-radius'     : toPx(val('th-radius', '16')),
    '--card-shadow'     : val('th-shadow', '0 10px 30px rgba(0,0,0,.25)'),

    /* Кнопки */
    '--btn-bg'          : val('th-btn-bg', '#ffffff'),
    '--btn-text'        : val('th-btn-text', '#111318'),
    '--btn-radius'      : toPx(val('th-btn-radius', '12')),
    '--btn-bg-ghost'    : val('th-btn-ghost-bg', '#262a34'),
    '--btn-text-ghost'  : val('th-btn-ghost-text', '#ffffff'),

    /* Таблиці */
    '--table-head-bg'   : val('th-table-head', '#242833'),
    '--table-row-hover' : val('th-table-row', '#1e212a'),
    '--table-border'    : val('th-table-border', '#2a2f3a'),
    '--table-cell-px'   : toPx(val('th-table-px', '16')),
    '--table-cell-py'   : toPx(val('th-table-py', '12')),

    /* Типографіка */
    '--base-fz'         : toPx(val('th-base-fz', '14')),
    '--font-weight'     : String(val('th-font-weight', '400')),
    '--heading-weight'  : String(val('th-heading-weight', '600')),
    '--font-style'      : String(val('th-font-style', 'normal')),

    /* Доповнення */

'--content-max'    : toPx(val('th-maxw', '1600')),   // загальна стеля контейнера

  };
}

// CSS із змінними
function toCss(vars) {
  const body = Object.entries(vars)
    .map(([k, v]) => `  ${k}: ${v};`)
    .join('\n');
  return `/* generated by theme.js */\n#admin-root{\n${body}\n}`;
}

// Застосувати тему
function applyTheme(vars) {
  styleTag.textContent = toCss(vars);
}

// Підтягнути активний профіль / списки
const readActive   = () => readJSON(LS_ACTIVE, {});
const writeActive  = (vars) => writeJSON(LS_ACTIVE, vars);
const readProfiles = () => readJSON(LS_PROFILES, {});
const writeProfiles= (map) => writeJSON(LS_PROFILES, map);

// Заповнити форму зі збережених змінних
function fillFormFrom(vars) {
  const set = (id, v) => { const el = safeGet(id); if (el && v != null) el.value = String(v).replace(/px|%/g,''); };

  // Layout
  set('th-content-x',        vars['--content-x']);
  set('th-gap',              vars['--admin-gap']);
  set('th-sidebar',          vars['--sidebar-w']);
  set('th-offset-left',      vars['--offset-left']);
  set('th-maxw',             vars['--panel-max-w']);
  set('th-tablew',           vars['--table-w']);

  // Панель налаштувань
  set('th-panel-mt',         vars['--settings-mt']);
  set('th-panel-mb',         vars['--settings-mb']);
  set('th-footer-h',         vars['--footer-h']);
  set('th-settings-maxw',    vars['--settings-maxw']);
  set('th-settings-w',       vars['--settings-width']);
  set('th-settings-minw',    vars['--settings-minw']);
  set('th-settings-zoom',    vars['--settings-zoom']);
  set('th-settings-gap',     vars['--settings-gap']);
  set('th-settings-pad-x',   vars['--settings-pad-x']);

  // Кольори
  set('th-c-page',           vars['--page-bg']);
  set('th-c-text',           vars['--text']);
  set('th-c-dim',            vars['--muted']);
  set('th-accent',           vars['--accent']);
  set('th-card-bg',          vars['--card-bg']);
  set('th-card-br',          vars['--card-br']);

  // Картки
  set('th-radius',           vars['--card-radius']);
  const sh = safeGet('th-shadow'); if (sh) sh.value = vars['--card-shadow'] || '0 10px 30px rgba(0,0,0,.25)';

  // Кнопки
  set('th-btn-bg',           vars['--btn-bg']);
  set('th-btn-text',         vars['--btn-text']);
  set('th-btn-radius',       vars['--btn-radius']);
  set('th-btn-ghost-bg',     vars['--btn-bg-ghost']);
  set('th-btn-ghost-text',   vars['--btn-text-ghost']);

  // Таблиці
  set('th-table-head',       vars['--table-head-bg']);
  set('th-table-row',        vars['--table-row-hover']);
  set('th-table-border',     vars['--table-border']);
  set('th-table-px',         vars['--table-cell-px']);
  set('th-table-py',         vars['--table-cell-py']);

  // Типографіка
  set('th-base-fz',          vars['--base-fz']);
  set('th-font-weight',      vars['--font-weight']);
  set('th-heading-weight',   vars['--heading-weight']);
  const fs = safeGet('th-font-style'); if (fs) fs.value = vars['--font-style'] || 'normal';
}

// Перезаповнити список профілів
function refreshSavedList() {
  const select = safeGet('th-saved'); if (!select) return;
  const profiles = readProfiles();
  const opts = ['<option value="">— Оберіть тему —</option>']
    .concat(Object.keys(profiles).sort().map(k => `<option value="${k}">${k}</option>`));
  select.innerHTML = opts.join('');
}

// Головна ініціалізація UI
export function initThemeUI() {
  const hasSettings = Boolean(document.querySelector('[data-admin-panel="settings"]'));
  if (!hasSettings) return;

  // 1) Активний профіль або дефолти з форми
  const active = readActive();
  if (active && Object.keys(active).length) {
    applyTheme(active);
    fillFormFrom(active);
  } else {
    const vars = collectVars();
    applyTheme(vars);
    writeActive(vars);
  }

  // 2) Live-оновлення при зміні будь-якого інпута (number, color, select, text)
  const container = document.querySelector('[data-admin-panel="settings"]');
  container?.addEventListener('input', (e) => {
    if (!(e.target instanceof HTMLInputElement) && !(e.target instanceof HTMLSelectElement)) return;
    // Не валимося, навіть якщо якогось поля немає
    try {
      const vars = collectVars();
      applyTheme(vars);
      writeActive(vars);
    } catch (err) {
      console.warn('[theme] collect/apply skipped:', err);
    }
  });

  // 3) Кнопки
  safeGet('th-apply')?.addEventListener('click', () => {
    const vars = collectVars(); applyTheme(vars); writeActive(vars);
  });

  safeGet('th-save')?.addEventListener('click', () => {
    const name = (safeGet('th-name')?.value || '').trim();
    if (!name) { alert('Вкажіть назву теми'); return; }
    const profiles = readProfiles();
    profiles[name] = collectVars();
    writeProfiles(profiles);
    writeActive(profiles[name]);
    refreshSavedList();
    alert('Тему збережено ✅');
  });

  safeGet('th-load')?.addEventListener('click', () => {
    const k = safeGet('th-saved')?.value || '';
    if (!k) return;
    const prof = readProfiles()[k];
    if (!prof) return;
    applyTheme(prof); writeActive(prof); fillFormFrom(prof);
  });

  safeGet('th-delete')?.addEventListener('click', () => {
    const k = safeGet('th-saved')?.value || '';
    if (!k) return;
    const profiles = readProfiles();
    delete profiles[k];
    writeProfiles(profiles);
    refreshSavedList();
  });

  safeGet('th-reset')?.addEventListener('click', () => {
    localStorage.removeItem(LS_ACTIVE);
    const vars = collectVars();
    applyTheme(vars); writeActive(vars);
  });

  refreshSavedList();
}

// Автовиклик (якщо модуль підключений напряму в сторінці)
document.addEventListener('DOMContentLoaded', () => {
  try { initThemeUI(); } catch (e) { console.error('[theme] init failed:', e); }
});


// — Кнопка: На всю ширину
const btnFull  = document.getElementById('btn-settings-full');
// — Кнопка: Фіксована ширина (повернутися до поля "Ширина панелі")
const btnFixed = document.getElementById('btn-settings-fixed');
// — Ручка-перетягування
const handle   = document.querySelector('.settings-resize-handle');
const root     = document.getElementById('admin-root');

btnFull?.addEventListener('click', () => {
  // 100vw мінус зовнішні відступи контенту, щоб не прилипало
  const px = (n) => `${Math.max(0, Number(n)||0)}px`;
  const pad = Number(val('th-content-x','24')) * 2;
  // розгортаємо контейнер і картку
  const vars = readActive();
  vars['--content-max']   = '100vw';
  vars['--panel-max-w']   = '100vw';
  vars['--settings-width']= `calc(100vw - ${px(pad)})`;
  applyTheme(vars); writeActive(vars);
});

btnFixed?.addEventListener('click', () => {
  // повертаємося до значень з полів "Макс. ширина панелі" та "Ширина панелі"
  const vars = collectVars();
  applyTheme(vars); writeActive(vars);
});

// Drag to resize
if (handle && root) {
  let startX = 0, startW = 0;
  const onMove = (ev) => {
    const dx = ev.clientX - startX;
    const min = parseFloat(getComputedStyle(root).getPropertyValue('--settings-minw')) || 720;
    const max = parseFloat(getComputedStyle(root).getPropertyValue('--settings-maxw')) || 1600;
    const next = Math.max(min, Math.min(max, startW + dx));
    const vars = readActive();
    vars['--settings-width'] = `${Math.round(next)}px`;
    applyTheme(vars); writeActive(vars);
  };
  const onUp = () => {
    document.removeEventListener('mousemove', onMove);
    document.removeEventListener('mouseup', onUp);
    document.body.style.userSelect = '';
    document.body.style.cursor = '';
  };
  handle.addEventListener('mousedown', (ev) => {
    const cs = getComputedStyle(root);
    startX = ev.clientX;
    startW = parseFloat(cs.getPropertyValue('--settings-width')) || 1100;
    document.addEventListener('mousemove', onMove);
    document.addEventListener('mouseup', onUp);
    document.body.style.userSelect = 'none';
    document.body.style.cursor = 'ew-resize';
  });
}